using System;

namespace Extensions
{
	// Component extension generated by Robot Studio 25.1.12.0
	[OpenSpan.DynamicMembers.Extensions.ExtendComponentAttribute("GlobalContainer-8DE7F83FFDDFDCB\\Counter-8DE85CC3640572F")]
	public class Counter1Extension : OpenSpan.ExpressTranslators.ExtensionBase
	{
		public Counter1Extension()
		{
		}
	}
}
